# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 00:17
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190417_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ar_id', models.AutoField(primary_key=True, serialize=False, verbose_name='文章ID')),
                ('title', models.CharField(max_length=100, verbose_name='文章标题')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章类容')),
                ('is_show', models.IntegerField(choices=[(1, '是'), (0, '否')], default=0, verbose_name='是否前端显示')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
                ('r_number', models.IntegerField(default=0, verbose_name='阅读数')),
                ('cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'zjm_article',
            },
        ),
    ]
