# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='intro',
            field=models.TextField(default='', verbose_name='简单描述'),
        ),
    ]
