# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-17 09:58
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章类容'),
        ),
    ]
